### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ikizhvatov** [s6juncheng/BERTMHC#3]
* BERTMHC version: git e79467a
* Python version: 3.9.1
* Operating System: Win10, Linux

### Description

Installation of the package under Win10 and Linux following README.md fails. Pip cannot find a suitable dependency, and trying to bypass this via conda fails as well. First due to custom numpy and pillow versions in requirements. Once I correct those conda still fails because it cannot find a number of dated package versions that are required.

Seems that rather old package versions in requirements, such as torch<1.5, are to blame.

### What I Did

```
git clone https://github.com/s6juncheng/BERTMHC.git; cd BERTMHC
conda create -n bert pip; conda activate bert
pip install .

ERROR: Could not find a version that satisfies the requirement torch<1.5,>=1.0 (from bertmhc)
ERROR: No matching distribution found for torch<1.5,>=1.0

conda install --file requirements.txt

CondaValueError: could not parse 'numpy @ file:///opt/concourse/worker/volumes/live/3f9886a9-9d2f-4d0a-7e31-acf5536b90f1/volume/numpy_and_numpy_base_1596234665264/work' in: requirements.txt

```

**Comment by s6juncheng** [comment]
Hi @ikizhvatov, can you try to create a new conda environment with python3.6 and then `pip install .` in the root repo? We only have the following dependencies in fact (already in setup):

```
requirements = [
    'setuptools',
    'torch>=1.0,<1.5',
    'pandas',
    'numpy',
    'tqdm',
    'tape_proteins',
    'scikit-learn',
    'scipy'
]
```

The conda environment indeed needs to be cleaned up. Will do it soon.

**Comment by ikizhvatov** [comment]
This worked. Thank you for the prompt response.

**Comment by s6juncheng** [comment]
Great, thanks
