### ISSUE TITLE
Input format conversion of MA data

### ISSUE THREAD

**Issue by KiAkize** [s6juncheng/BERTMHC#5]
How to convert the EL data provided by NetMHCIIpan4.0 into the required format?

**Q1**: Set the `label` of all EL data to 0?

For MA data, the allele provided by NetMHCIIpan4.0 actually contains multiple alleles in a cell line. 
**Q2**: For the positive sample of MA data, traverse all alleles contained in the cell line and set `masslable` to 1, `MA` to True, how to set `group_index`?

**Q3**: Similarly, how to transform the negative sample of MA data?

**Comment by s6juncheng** [comment]
Q1 yes
Q2 yes, the group_index refers to a unique index assigned to the set of multiple alleles (bag), all alleles in the set has the same unique index so that we know they belong to the same set. You could assign them from 0 to n. 
Q3 as Q2

**Comment by KiAkize** [comment]
And when training, set `--alpha 1 --deconvolution True --calibrate True` ?

**Comment by KiAkize** [comment]
What configuration did you use for training with all EL data?
How many gpus did you use?
 How many hours did you train for 30 epochs?

**Comment by s6juncheng** [comment]
The EL model is heavy to train, we are working on having a webserver to server predictions.
