### ISSUE TITLE
MHCII allele pseudo-sequences

### ISSUE THREAD

**Issue by Marython** [s6juncheng/BERTMHC#6]
* Python version: 3.7.4
* Operating System: Chrome Mac OS
* Non-commercial research [Y/N]: Y

### Description

Dear BertMHC authors, 

I was wondering whether the MHCII allele pseudo-sequences, used as an input feature, could be shared in the repository to facilitate the use of the model? 

Thank you in advance for your help, 
Marie Lopez

**Comment by s6juncheng** [comment]
Dear Marie Lopez,

We are not allowed to share this for license reasons. If you are interested in trying the model, we are working to open a webserver where you could just upload your peptides to get predictions. It will come in a few days. Thanks.

Best,
Jun

**Comment by Marython** [comment]
Dear Jun Cheng,

Thank you very much for your prompt answer. I can't wait to try the webserver!

Best,
Marie

**Comment by Yiming-Shen** [comment]
Hi Jun,

I tried BERTmhc few weeks ago, however, it seems that the webserver service is currently unavailable. The link from README shows "503 Service Unavailable". Hope it can get online again soon.

Best,
Yiming

**Comment by s6juncheng** [comment]
Hi Yiming,

The server was under maintenance, now should be available again. We have a new GPU server that arrived, should be configured end of the month, you could as well try by then for a better user experience. 

Best,
Jun

**Comment by s6juncheng** [comment]
Dear @Marython and @Yiming-Shen,

We just updated the server hardware. Please feel free to try it out and let us know how your feedback. You can submit max 5k peptides per query. 

Best,
Jun

**Comment by nasserhashemi** [comment]
Hi @s6juncheng 

Thanks for sharing your great job; It seems that there are some allele in your independent test set which is not covered in Netmhcpan; I was wondering if you would let me know how you get the pseudo-seq of them. Thanks 

here is the list of alleles: 
HLA-DRA10101-DRB10101',
 'HLA-DRA10101-DRB10103',
 'HLA-DRA10101-DRB10301',
 'HLA-DRA10101-DRB10401',
 'HLA-DRA10101-DRB10404',
 'HLA-DRA10101-DRB10407',
 'HLA-DRA10101-DRB10701',
 'HLA-DRA10101-DRB10801',
 'HLA-DRA10101-DRB10901',
 'HLA-DRA10101-DRB11001',
 'HLA-DRA10101-DRB11301',
 'HLA-DRA10101-DRB11501',
 'HLA-DRA10101-DRB30101',
 'HLA-DRA10101-DRB30202',
 'HLA-DRA10101-DRB40101',
 'HLA-DRA10101-DRB50101'}
