### ISSUE TITLE
Can I start training the model at a checkpoint?

### ISSUE THREAD

**Issue by josiehong** [s6juncheng/BERTMHC#7]
* BERTMHC version: 0.1.0
* Python version: 3.7.11
* Operating System: Ubuntu 18.04.5 LTS
* Non-commercial research [Y/N]: Y

### Description

Hi, Jun,

Thanks for your great work of BERTMHC. I am trying to train BERTMHC on custom data, and I am curious about that whether I can start training the model at a checkpoint (a previously trained model). Thanks. 

Best,
Josie

**Comment by s6juncheng** [comment]
Hi Josie,

You should be able to retrain the model from the same publicly available datasets easily with the open-source code. In this case, the pretrained checkpoints are only available for inference from the webserver.  

Best,
Jun
